idf_component_register(
    SRCS
        "main.c"
        "wifi_sta_ui.c"
        "ytmd_client.c"
        "ui/images.c"
        "ui/screens.c"
        "ui/styles.c"
        "ui/ui.c"
        "ui/ui_font_font_jp_14.c"
        "ui/ui_font_font_jp_16.c"
        "ui/ui_font_font_kor_14.c"
        "ui/ui_font_font_kor_16.c"
    INCLUDE_DIRS
        "."
        "ui"
    REQUIRES
        driver
        esp_driver_ledc
        esp_lcd
        esp_event
        esp_http_client
        esp_netif
        esp_timer
        esp_wifi
        esp_new_jpeg
        lvgl
        nvs_flash)
